#pragma once

#include <Box2D/Box2D.h>

enum class UserDataType {
    Player,
    Zombie,
    PlayerBullet,
    ZombieBullet,
    FireBullet,
    Market,
    BatHit,
    LoadMap,
    Gift
};

struct UserData {
    void* object;
    UserDataType type;
    uint16 categoryBits;
    uint16 maskBits;
};

namespace Collision {
    enum Category {
        PLAYER = 0x0001,
        ZOMBIE_MELEE = 0x0002,
        ZOMBIE_RANGED = 0x0004,
        ZOMBIE_BOSS = 0x0008,
        PLAYER_BULLET = 0x0010,
        ZOMBIE_BULLET = 0x0020,
        FIRE_BULLET = 0x0040,
        BAT_HIT = 0x0080,
        WATER = 0x0100,
        MIDDLE_WALL = 0x0200,
        BOUNDARY_WALL = 0x0400,
        MARKET = 0x0800
    };

    // Collision masks
    constexpr uint16 PLAYER_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | ZOMBIE_BULLET | FIRE_BULLET | BAT_HIT | WATER | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 ZOMBIE_MELEE_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | FIRE_BULLET | BAT_HIT | WATER | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 ZOMBIE_RANGED_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | FIRE_BULLET | BAT_HIT | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 ZOMBIE_BOSS_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | FIRE_BULLET | BAT_HIT | BOUNDARY_WALL | MARKET;
    constexpr uint16 PLAYER_BULLET_MASK = ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 ZOMBIE_BULLET_MASK = PLAYER | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 FIRE_BULLET_PLAYER_MASK = ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS;
    constexpr uint16 FIRE_BULLET_ZOMBIE_MASK = PLAYER;
    constexpr uint16 BAT_HIT_PLAYER_MASK = ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | MIDDLE_WALL | BOUNDARY_WALL | MARKET;
    constexpr uint16 WATER_MASK = PLAYER | ZOMBIE_MELEE;
    constexpr uint16 MIDDLE_WALL_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | PLAYER_BULLET | ZOMBIE_BULLET | FIRE_BULLET | BAT_HIT;
    constexpr uint16 BOUNDARY_WALL_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | ZOMBIE_BULLET | FIRE_BULLET | BAT_HIT;
    constexpr uint16 MARKET_MASK = PLAYER | ZOMBIE_MELEE | ZOMBIE_RANGED | ZOMBIE_BOSS | PLAYER_BULLET | ZOMBIE_BULLET | FIRE_BULLET | BAT_HIT;
    constexpr int16 PLAYER_GROUP = -1;
    constexpr int16 ZOMBIE_GROUP = -2;
}
